spring:
  application:
    name: pethub
  mvc:
    view:
      suffix: .html

  #데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.36.207.45:3306/pethub?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 12345678

  #타임리프 경로 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  #Support Mail Service
  mail:
    host: smtp.gmail.com
    port: 587
    username: rkdgur96@gmail.com
    password: nqke pyrb waog kgle
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true


#server port 변경
server:
  port: 8081
